export const DEFAULT_BOOKMARK_KEY = "bookmark-recipes";
export const DEFAULT_SEARCH_PLACEHOLDER = "chicken";

export const FILTER_OPTIONS = [
  {
    label: "Diet",
    subOptions: [
      "balanced",
      "high-fiber",
      "high-protein",
      "low-carb",
      "low-fat",
      "low-sodium",
    ],
  },
  {
    label: "Health",
    subOptions: [
      "alcohol-cocktail",
      "alcohol-free",
      "celery-free",
      "crustacean-free",
      "dairy-free",
      "DASH",
      "egg-free",
      "fish-free",
      "gluten-free",
      "immuno-supportive",
      "keto-friendly",
      "kidney-friendly",
      "kosher",
      "low-fat-abs",
      "low-potassium",
      "low-sugar",
      "lupin-free",
      "mediterranean",
      "mollusk-free",
      "mustard-free",
      "no-Oil-added",
      "paleo",
      "peanut-free",
      "pescatarian",
      "pork-free",
      "red-Meat-free",
      "sesame-free",
      "shellfish-free",
      "soy-free",
      "sugar-conscious",
      "sulfite-free",
      "tree-nut-free",
      "vegan",
      "vegetarian",
      "wheat-free",
    ],
  },
  {
    label: "Cuisine Type",
    subOptions: [
      "American",
      "Asian",
      "British",
      "Caribbean",
      "Central Europe",
      "Chinese",
      "Eastern Europe",
      "French",
      "Indian",
      "Italian",
      "Japanese",
      "Kosher",
      "Mediterranean",
      "Mexican",
      "Middle Eastern",
      "Nordic",
      "South American",
      "Southeast Asian",
    ],
  },
  {
    label: "Meal Type",
    subOptions: ["Breakfast", "Lunch", "Dinner", "Teatime", "Snack"],
  },
  {
    label: "Dish Type",
    subOptions: [
      "Biscuits and Cookies",
      "Bread",
      "Cereals",
      "Condiments and Sauces",
      "Desserts",
      "Drinks",
      "Main Course",
      "Pancake",
      "Preps",
      "Preserve",
      "Salad",
      "Sandwiches",
      "Side Dish",
      "Soup",
      "Starter",
      "Sweets",
    ],
  },
  { label: "Calories", subOptions: [] },
];
